font, logo, 색상을 root에 추가
DevBadgers/starchive pull request #11
Opened 2024-11-20 11:20 UTC by thanhhien234

### 🔍 개요

font, logo, 색상을 root에 추가

### ✨ 작업 내용

- logo.png를 assets에 추가
- font, color를 index.css에 추가
- 텍스트 스타일을 App.css

### ✅ 체크리스트

- [x] 코드가 제대로 빌드되는지 확인했습니다.
- [ ] 관련 테스트 케이스를 추가/수정했습니다.
- [x] 문서(예: README, API 문서)가 업데이트되었거나 업데이트가 필요하지 않습니다.
- [ ] PR에 연결된 이슈가 있는 경우, 해당 이슈 번호를 링크했습니다.

### 🔗 관련 이슈

### 💬 리뷰 요구사항 (option)
font-family에 폰트 2개를 추가했는데 언제 Poppins인지 언제 Noto Sans KR인지 모르겠어요

### 📎 추가 정보 (option)

2024-11-20 13:58 UTC, hanguswls approved these changes
영어일 때 Poppins, 한글일 때 Noto sans 였던 것 같아요!

2024-11-21 00:53 UTC, JongHyeok-Park requested changes
PR 제목도 주석에 해놓은 것처럼 앞에 [Feature]는 안 적어도 됩니다.

2024-11-21 00:53 UTC, JongHyeok-Park commented on FRONT/src/index.css
> +  font-family: 'Poppins', 'Noto Sans KR', sans-serif;
Noto Sans KR이 먼저 와야합니다.

2024-11-21 01:06 UTC, JongHyeok-Park requested changes

2024-11-21 01:06 UTC, JongHyeok-Park commented on FRONT/src/assets/logo/logo.png
그리고 이거 svg 파일로 해주세여

2024-11-21 01:19 UTC, JongHyeok-Park approved these changes

2024-11-21 01:19 UTC, merged