Aside 컴포넌트 (#5)
DevBadgers/starchive pull request #19
Opened 2024-11-24 12:38 UTC by hanguswls

### 🔍 개요

Aside 컴포넌트 추가
### ✨ 작업 내용

- assets/icons에 cancel-button, category-toggle-button 추가
- Aside 컴포넌트 구현
- Aside 열림/닫힘 훅 구현
- 임의의 카테고리 데이터 추가

### ✅ 체크리스트

- [x] 코드가 제대로 빌드되는지 확인했습니다.
- [x] 문서(예: README, API 문서)가 업데이트되었거나 업데이트가 필요하지 않습니다.
- [x] PR에 연결된 이슈가 있는 경우, 해당 이슈 번호를 링크했습니다.

### 🔗 관련 이슈

#5 
### 💬 리뷰 요구사항 (option)

### 🔍 개요

Aside 컴포넌트 추가
### ✨ 작업 내용

- assets/icons에 cancel-button, category-toggle-button 추가
- Aside 컴포넌트 구현
- Aside 열림/닫힘 훅 구현
- 임의의 카테고리 데이터 추가

### ✅ 체크리스트

- [x] 코드가 제대로 빌드되는지 확인했습니다.
- [x] 문서(예: README, API 문서)가 업데이트되었거나 업데이트가 필요하지 않습니다.
- [x] PR에 연결된 이슈가 있는 경우, 해당 이슈 번호를 링크했습니다.

### 🔗 관련 이슈

#5 

### 💬 리뷰 요구사항 (option)

- Category 인터페이스가 CategoryNode.tsx와 useAside.ts 두 파일에서 각각 정의되어 중복되고 있습니다.
이를 별도의 타입 파일로 분리해서 import하는 게 좋을까요?
- ../../assets도 @_assets로 alias을 추가해서 바꾸는 것이 좋을까요?
- Aside의 열림/닫힘 상태를 전역으로 관리하는 것이 좋을것같은데, 전역 상태 관리 도구(Zustand)를 설치하지 않았어요

### 📎 추가 정보 (option)
![image](https://github.com/user-attachments/assets/4db174be-debc-4183-bfcc-d72152e29396)

2024-11-24 18:27 UTC, JongHyeok-Park requested changes

2024-11-24 18:27 UTC, JongHyeok-Park commented on FRONT/src/components/Aside/useAside.ts
이거 지금 두 컴포넌트에서 사용하는 기능을 한곳에 다 때려넣은 파일 같은데 분리해야하지 않을까요? 이러면 CategoryNode를 따로 작성할 필요가 없지 않나요?

2024-11-24 18:29 UTC, JongHyeok-Park commented on FRONT/src/components/Aside/useAside.ts
> +  const navigate = useNavigate();
이거 지금 사용 안된다고 lint에서 에러 떠가지구 빌드가 안되네요. 안쓰면 주석처리 하셔야 할 것 같은데..

2024-11-25 05:27 UTC, hanguswls commented
수정했습니다
그리고 `isAsideOpen`, `setIsAsideOpen`을 전역으로 바꿨습니다

2024-11-25 06:14 UTC, JongHyeok-Park approved these changes
zustand 쓴 거는 잘 모르겠네요. 사실 navbar 말고는 그 상태를 참조할 필요가 있나..? 싶은데 일단 그대로 합시다.

그리고 `interface` 반복되는 거에서 솔루션 하나 드리자면 해당 `components` 폴더에서 `types` 라는 폴더를 하나 만들어서 그 안에 구성해놔도 좋을 것 같아요.

2024-11-25 06:52 UTC, hanguswls commented
Aside/types/Category.ts에 interface Category를 분리했습니다
나중에 글을 작성할 때 Category 인터페이스가 쓰인다면 그때 파일 위치를 이동시켜도 될 것 같습니다

2024-11-26 07:38 UTC, JongHyeok-Park commented on FRONT/src/components/Aside/types/Category.ts
첫문자 대문자 말고 소문자로 하시면 됩니다.

2024-11-26 07:39 UTC, JongHyeok-Park commented on FRONT/src/components/Aside/types/Category.ts
이렇게 하면 Aside 내에서 category 관련 도메인의 타입들을 정의하는 겁니다.

2024-11-26 07:40 UTC, JongHyeok-Park commented on FRONT/src/components/Aside/category.example.json
갑자기 생각났는데 요런 거 그 public에 폴더 하나 만들어서 넣어두고 api 요청하는 방법으로 테스트해봐도 좋겠네요. 그러면 그냥 파일을 import 하는게 아니라 api 요청으로 코드를 짤 수 있겠네요.

2024-11-26 07:40 UTC, JongHyeok-Park commented on FRONT/src/components/Aside/category.example.json
일단 merge하고 작업하시면 될 것 같아요 ㅎㅎ

2024-11-26 07:43 UTC, JongHyeok-Park commented on FRONT/src/components/Aside/Aside.tsx
> +          ))}
```
{
   category.map((topCategory: Category) => (
      <TopCategoryItem key={topCategory.id}>
         <CategoryNode
             category={topCategory}
                onSelect={handleCategorySelect}
             activeCategoryId={activeCategoryId}
          />
         </TopCategoryItem>
    ))
}
```
코드 스타일 일정하게 합시다.

2024-11-26 07:51 UTC, thanhhien234 approved these changes

2024-11-26 08:09 UTC, JongHyeok-Park commented on FRONT/src/components/Aside/components/useCategoryNode.ts
> +function useCategoryNode(): { isOpen: boolean; handleToggle: (e: React.MouseEvent) => void } {
그러네

2024-11-26 11:52 UTC, hanguswls commented on FRONT/src/components/Aside/category.example.json
옙 그럼 일단 merge 해놓고 수정하겠습니다

2024-11-26 11:53 UTC, merged